export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const MAP_LOADED = 'MAP_LOADED'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const UPLOAD_IMAGE_BEGIN = 'UPLOAD_IMAGE_BEGIN';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';

export const CREATE_HAZARD_BEGIN = 'CREATE_HAZARD_BEGIN';
export const CREATE_HAZARD_SUCCESS = 'CREATE_HAZARD_SUCCESS';
export const CREATE_HAZARD_ERROR = 'CREATE_HAZARD_ERROR';

export const GET_ALL_HAZARDS_BEGIN = 'GET_ALL_HAZARDS_BEGIN';
export const GET_ALL_HAZARDS_SUCCESS = 'GET_ALL_HAZARDS_SUCCESS';

export const CREATE_ROUND_BEGIN = 'CREATE_ROUND_BEGIN';
export const CREATE_ROUND_SUCCESS = 'CREATE_ROUND_SUCCESS';
export const CREATE_ROUND_ERROR = 'CREATE_ROUND_ERROR';

export const GET_ONE_ROUND_BEGIN = 'GET_ONE_ROUND_BEGIN';
export const GET_ONE_ROUND_SUCCESS = 'GET_ONE_ROUND_SUCCESS';

export const SET_ROUND = 'SET_ROUND'



export const LOGOUT_USER = 'LOGOUT_USER';
